# Site settings
title_left: "pert"
title_right: "sauce" # default: ""
description: "Albert Kragl"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace, albert, kragl, kraglalbert, pertsauce, pert"
url: https://kraglalbert.github.io # site url
baseurl: "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo

google_analytics: UA-130499534-1
twitter_username: ""
comments_enabled: true # if enabled (set to true), please provide your disqus_username
disqus_shortname: "albertkragl"
postshare_enabled: true

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Albert Kragl"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  - slug: contact
    title: Contact

exclude:
  [
    "gulp",
    "node_modules",
    "bower",
    "bower_components",
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    ".rvmrc",
    ".rbenv-version",
    "package.json",
    "gulpfile.js",
    "README.md",
    "Rakefile",
    "changelog.md",
    "script",
  ]
